# port
server:
  port: 8765

# DataSource
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lanhuigu?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver

# MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# rocketmq
rocketmq:
  producer:
    testProducer:
      namesrvAddr: 10.6.202.110:9876;10.6.202.111:9876
      groupName: testProducerGroup
      topic: testTopic
      instanceName: testProducerInstance
  consumer:
    testConsumer:
      namesrvAddr: 10.6.202.110:9876;10.6.202.111:9876
      groupName: testConsumerGroup
      topic: testTopic
      tag: '*'
      batchMaxSize: 16
      instanceName: testConsumerInstance